version: "3.8"
services:
    web:
        image: guguchkovd/bgapp-web-nginx:1.0
        deploy:
            replicas: 3
        ports:
            - 8081:8080
        networks:
            - app-network
    db:
        image: guguchkovd/bgapp_db_nginx
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
networks:
    app-network:
