version: "3.8"
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.web
        ports:
            - 8081:8080
        networks:
            - app-network
    db:
        build:
            context: .
            dockerfile: Dockerfile.db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
networks:
    app-network:
